export const SET_API_IMAGES = 'SET_API_IMAGES';
export const FETCHED_PAGE = 'FETCHED_PAGE';
export const FETCHED_REVIEWS = 'FETCHED_REVIEWS';
export const FETCHED_MOVIE = 'FETCHED_MOVIE';

export const ADD_TO_FAVORITES = 'ADD_TO_FAVORITES';
export const REMOVE_FROM_FAVORITES = 'REMOVE_FROM_FAVORITES';
export const SET_FAVORITES = 'SET_FAVORITES';

export const NOTIFY_IDLE = 'NOTIFY_IDLE';
export const NOTIFY_FETCHING = 'NOTIFY_FETCHING';
export const NOTIFY_ERROR = 'NOTIFY_ERROR';

export const SET_SNACKBAR_ENQUEUER = 'SET_SNACKBAR_ENQUEUER';
export const ENQUEUE_NOTIFICATION = 'ENQUEUE_NOTIFICATION';
